package agentservice

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/lovitus/dragfm-gui/internal/agentlease"
)

// ServeCommand supervises only the SCP/rsync server forms generated by the
// transfer libraries. It runs under the authenticated SSH account, never sudo
// here, and inherits the already-held installation lease. No shell evaluation
// or credentials/configuration files are involved; stdin is the native stream.
func ServeCommand(ctx context.Context, args []string, input, output, diagnostic *os.File) error {
	if selfDirectory() == "" {
		return errors.New("transfer server requires an owned helper installation")
	}
	if err := validateServerCommand(args); err != nil {
		return err
	}
	var binary string
	for _, directory := range []string{"/usr/bin", "/bin"} {
		candidate := filepath.Join(directory, args[0])
		if info, err := os.Stat(candidate); err == nil && info.Mode().IsRegular() && info.Mode().Perm()&0111 != 0 {
			binary = candidate
			break
		}
	}
	if binary == "" {
		return fmt.Errorf("system %s server is unavailable", args[0])
	}
	command := exec.CommandContext(ctx, binary, args[1:]...)
	configureChildLifecycle(command)
	command.WaitDelay = 2 * time.Second
	command.Stdin, command.Stdout, command.Stderr = input, output, diagnostic
	if err := agentlease.Attach(ctx, command); err != nil {
		return err
	}
	return command.Run()
}

func validateServerCommand(args []string) error {
	if len(args) < 3 || !filepath.IsAbs(args[len(args)-1]) || strings.ContainsRune(strings.Join(args, ""), 0) {
		return errors.New("invalid transfer server arguments")
	}
	switch args[0] {
	case "scp":
		mode := 0
		for _, arg := range args[1 : len(args)-1] {
			switch arg {
			case "-f", "-t":
				mode++
			case "-p", "-r", "-d":
			default:
				return errors.New("unsupported SCP server option")
			}
		}
		if mode != 1 {
			return errors.New("SCP requires exactly one server direction")
		}
	case "rsync":
		if len(args) < 5 || args[1] != "--server" || args[len(args)-2] != "." {
			return errors.New("rsync requires server mode and one absolute operand")
		}
		for _, arg := range args[2 : len(args)-2] {
			if arg == "--sender" {
				continue
			}
			// -a's generated server capability letters vary by rsync version.
			// Permit that short-letter word, not remote shell/config/daemon
			// options or additional path operands.
			if len(arg) < 2 || arg[0] != '-' || strings.Trim(arg[1:], "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.") != "" {
				return errors.New("unsupported rsync server option")
			}
		}
	default:
		return errors.New("unsupported transfer server")
	}
	return nil
}
