package agentservice

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"strconv"
	"time"

	"github.com/lovitus/dragfm-gui/internal/activity"
	"github.com/lovitus/dragfm-gui/internal/agentlease"
	"github.com/lovitus/dragfm-gui/internal/agentproto"
)

// Serve reads ahead only enough to observe EOF on the authenticated SSH
// control stream. Losing that stream cancels in-flight children immediately.
// Heartbeats are generated by the actual remote helper, not by a UI timer.
func Serve(ctx context.Context, protocol *agentproto.Conn) (resultErr error) {
	life, cancel := context.WithCancel(ctx)
	observed, counters := activity.WithObserver(life, nil)
	service := NewWithContext(observed)
	defer func() {
		cancel()
		cleanupErr := service.Close()
		if directory := selfDirectory(); cleanupErr == nil && directory != "" {
			cleanupErr = removeOwnedTemp(service.ctx, directory)
			if errors.Is(cleanupErr, os.ErrNotExist) {
				cleanupErr = nil // Acknowledged remove-owned-temp already removed it.
			}
		}
		resultErr = errors.Join(resultErr, cleanupErr)
	}()
	requests := make(chan agentproto.Request)
	readDone := make(chan error, 1)
	go func() {
		for {
			var request agentproto.Request
			if err := protocol.Receive(&request); err != nil {
				readDone <- err
				cancel()
				return
			}
			select {
			case requests <- request:
			case <-life.Done():
				return
			}
		}
	}()
	for {
		select {
		case <-life.Done():
			return life.Err()
		case request := <-requests:
			result := make(chan agentproto.Response, 1)
			go func() { result <- service.Handle(request) }()
			timer := time.NewTicker(time.Second)
			var response agentproto.Response
			running := true
			for running {
				select {
				case response = <-result:
					running = false
				case <-timer.C:
					if request.Options["progress"] == "true" {
						heartbeat := agentproto.Response{Version: agentproto.ProtocolVersion, ID: request.ID, OK: true, Progress: true, Values: map[string]string{"action": request.Action, "wire_bytes": strconv.FormatInt(counters.Bytes(), 10)}}
						if err := protocol.Send(heartbeat); err != nil {
							cancel()
						}
					}
				case <-life.Done():
					timer.Stop()
					// CommandContext and transport cancellation must finish before cleanup.
					select {
					case <-result:
					case <-time.After(4 * time.Second):
					}
					return life.Err()
				}
			}
			timer.Stop()
			if err := protocol.Send(response); err != nil {
				return err
			}
		case err := <-readDone:
			if errors.Is(err, io.EOF) {
				return nil
			}
			return err
		}
	}
}

// Close terminates helper-owned children/listeners before scoped filesystem
// cleanup. It is also used when the controller disappears unexpectedly.
func (s *Service) Close() error {
	s.closeOnce.Do(func() { s.closeErr = s.close() })
	return s.closeErr
}

func (s *Service) close() error {
	s.mu.Lock()
	s.closing = true
	s.cancel()
	s.mu.Unlock()
	idle := make(chan struct{})
	go func() { s.active.Wait(); close(idle) }()
	select {
	case <-idle:
	case <-time.After(3 * time.Second):
		return errors.New("helper request did not stop; partials and installation retained")
	}
	s.mu.Lock()
	ids := make([]string, 0, len(s.processes))
	for id := range s.processes {
		ids = append(ids, id)
	}
	listeners := s.jobs
	s.jobs = make(map[string]*listenerJob)
	s.mu.Unlock()
	for _, job := range listeners {
		if job.cancel != nil {
			job.cancel()
		}
		_ = job.listener.Close()
	}
	var failures []error
	for _, id := range ids {
		if err := s.stopProcess(id); err != nil {
			failures = append(failures, fmt.Errorf("stop helper child: %w", err))
		}
	}
	deadline := time.NewTimer(3 * time.Second)
	defer deadline.Stop()
	for _, job := range listeners {
		select {
		case <-job.done:
		case <-deadline.C:
			// A still-running receiver owns these files. Never race its writes
			// by deleting the tree; expired markers permit later cleanup.
			return errors.Join(append(failures, errors.New("receiver did not stop; partials and installation retained"))...)
		}
	}
	if err := errors.Join(failures...); err != nil {
		return err
	}
	// Also covers independent SFTP channels and inherited child descriptors.
	// Neither local channel Close nor the helper PID's death proves quiescence.
	if err := agentlease.Guard(s.ctx); err != nil {
		return err
	}
	return s.cleanupPartials()
}
