package agentservice

import (
	"context"
	"errors"
	"io"
	"strconv"
	"time"

	"github.com/lovitus/dragfm-gui/internal/activity"
	"github.com/lovitus/dragfm-gui/internal/agentproto"
)

// Serve reads ahead only enough to observe EOF on the authenticated SSH
// control stream. Losing that stream cancels in-flight children immediately.
// Heartbeats are generated by the actual remote helper, not by a UI timer.
func Serve(ctx context.Context, protocol *agentproto.Conn) error {
	life, cancel := context.WithCancel(ctx)
	observed, counters := activity.WithObserver(life, nil)
	service := NewWithContext(observed)
	defer func() { cancel(); service.Close() }()
	requests := make(chan agentproto.Request)
	readDone := make(chan error, 1)
	go func() {
		for {
			var request agentproto.Request
			if err := protocol.Receive(&request); err != nil {
				readDone <- err
				cancel()
				return
			}
			select {
			case requests <- request:
			case <-life.Done():
				return
			}
		}
	}()
	for {
		select {
		case <-life.Done():
			return life.Err()
		case request := <-requests:
			result := make(chan agentproto.Response, 1)
			go func() { result <- service.Handle(request) }()
			timer := time.NewTicker(time.Second)
			var response agentproto.Response
			running := true
			for running {
				select {
				case response = <-result:
					running = false
				case <-timer.C:
					if request.Options["progress"] == "true" {
						heartbeat := agentproto.Response{Version: agentproto.ProtocolVersion, ID: request.ID, OK: true, Progress: true, Values: map[string]string{"action": request.Action, "wire_bytes": strconv.FormatInt(counters.Bytes(), 10)}}
						if err := protocol.Send(heartbeat); err != nil {
							cancel()
						}
					}
				case <-life.Done():
					timer.Stop()
					// CommandContext and transport cancellation must finish before cleanup.
					select {
					case <-result:
					case <-time.After(4 * time.Second):
					}
					return life.Err()
				}
			}
			timer.Stop()
			if err := protocol.Send(response); err != nil {
				return err
			}
		case err := <-readDone:
			if errors.Is(err, io.EOF) {
				return nil
			}
			return err
		}
	}
}

// Close terminates helper-owned children/listeners before scoped filesystem
// cleanup. It is also used when the controller disappears unexpectedly.
func (s *Service) Close() {
	s.mu.Lock()
	ids := make([]string, 0, len(s.processes))
	for id := range s.processes {
		ids = append(ids, id)
	}
	for _, job := range s.jobs {
		_ = job.listener.Close()
	}
	s.mu.Unlock()
	for _, id := range ids {
		_ = s.stopProcess(id)
	}
	s.cleanupPartials()
}
